server:
  port: 10011

spring:
  application:
    name: nacos-regist
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.145:80
        namespace: 65cc6807-1077-44c9-aabe-289a2d4c5be2
