server:
  port: 20011

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.168.1.13:10011
        namespace: 65cc6807-1077-44c9-aabe-289a2d4c5be2
